---
branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
      releaseRules:
        - breaking: true
          release: major
        - type: ci
          release: patch
        - type: chore
          release: patch
        - type: refactor
          release: patch
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: refactor
            section: Improvements
          - type: docs
            section: Documentation
          - type: style
            section: Misc
          - type: chore
            section: Misc
          - type: perf
            section: Performance
          - type: test
            section: Testing
          - type: build
            section: Build System
          - type: ci
            section: Continuous Integration
          - type: revert
            section: Reverts
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
      changelogTitle: |-
        # Changelog

        All notable changes to this project are documented in this file. See
        [Conventional Commits](https://www.conventionalcommits.org) for commit guidelines.
  - '@semantic-release/github'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
      message: 'chore(release): ${nextRelease.version} [skip ci]'
