---
version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  mcp-schema-download:
    desc: "Download the latest MCP schema and convert to YAML"
    cmds:
      - npm install js-yaml
      - curl -o mcp/mcp-schema.json https://raw.githubusercontent.com/modelcontextprotocol/modelcontextprotocol/refs/heads/main/schema/draft/schema.json
      - |
        echo "Converting JSON schema to YAML format"
        NODE_PATH=./node_modules:${NODE_PATH:-/usr/lib/node_modules} node -e "
          const fs = require('fs');
          const yaml = require('js-yaml');
          const json = JSON.parse(fs.readFileSync('mcp/mcp-schema.json', 'utf8'));
          fs.writeFileSync('mcp/mcp-schema.yaml', yaml.dump(json, {lineWidth: -1}));
        "

  a2a-schema-download:
    desc: "Generate JSON schema from A2A proto and convert to YAML"
    cmds:
      - npm install js-yaml
      - go install github.com/bufbuild/protoschema-plugins/cmd/protoc-gen-jsonschema@latest
      - mkdir -p a2a/tmp
      - cp a2a/a2a.proto a2a/tmp/a2a.proto
      - curl -o a2a/tmp/buf.yaml https://raw.githubusercontent.com/google-a2a/A2A/main/specification/grpc/buf.yaml
      - |
        echo "Converting proto to JSON schema using buf and protoc"
        cat > a2a/tmp/buf.gen.yaml <<EOF
        version: v2
        plugins:
          - local: protoc-gen-jsonschema
            out: ..
            opt: target=json-strict-bundle
        EOF
        cd a2a/tmp
        buf dep update
        PATH="$(go env GOPATH)/bin:$PATH" buf generate
        cd ../..
      - |
        echo "Processing bundled schema"
        NODE_PATH=./node_modules:${NODE_PATH:-/usr/lib/node_modules} node scripts/process-bundle.js
      - |
        echo "Adding required fields from proto annotations"
        NODE_PATH=./node_modules:${NODE_PATH:-/usr/lib/node_modules} node scripts/add-required-fields.js
      - rm -rf a2a/tmp

  openapi:format:
    desc: "Format OpenAPI Spec"
    cmds:
      - prettier --write openapi.yaml

  openapi:lint:
    desc: "Lint OpenAPI spec"
    cmds:
      - spectral lint --verbose openapi.yaml
