---
version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  mcp-schema-download:
    desc: "Download the latest MCP schema and convert to YAML"
    cmds:
      - npm install js-yaml
      - curl -o mcp/mcp-schema.json https://raw.githubusercontent.com/modelcontextprotocol/modelcontextprotocol/refs/heads/main/schema/draft/schema.json
      - |
        echo "Converting JSON schema to YAML format"
        NODE_PATH=./node_modules:${NODE_PATH:-/usr/lib/node_modules} node -e "
          const fs = require('fs');
          const yaml = require('js-yaml');
          const json = JSON.parse(fs.readFileSync('mcp/mcp-schema.json', 'utf8'));
          fs.writeFileSync('mcp/mcp-schema.yaml', yaml.dump(json, {lineWidth: -1}));
        "

  a2a-schema-download:
    desc: "Download the latest A2A proto and generate JSON schema, then convert to YAML"
    cmds:
      - npm install js-yaml
      - go install github.com/chrusty/protoc-gen-jsonschema/cmd/protoc-gen-jsonschema@latest
      - mkdir -p a2a/tmp
      - curl -o a2a/tmp/a2a.proto https://raw.githubusercontent.com/google-a2a/A2A/main/specification/grpc/a2a.proto
      - curl -o a2a/tmp/buf.yaml https://raw.githubusercontent.com/google-a2a/A2A/main/specification/grpc/buf.yaml
      - |
        echo "Converting proto to JSON schema using buf and protoc"
        cat > a2a/tmp/buf.gen.yaml <<EOF
        version: v2
        plugins:
          - local: protoc-gen-jsonschema
            out: ..
            opt:
              - enums_as_strings_only
              - type_names_with_no_package
        EOF
        cd a2a/tmp
        buf dep update
        PATH="$(go env GOPATH)/bin:$PATH" buf generate
        cd ../..
      - |
        echo "Merging individual JSON schemas into single schema"
        NODE_PATH=./node_modules:${NODE_PATH:-/usr/lib/node_modules} node -e "
          const fs = require('fs');
          const path = require('path');
          const yaml = require('js-yaml');

          const combinedSchema = {
            '\$schema': 'http://json-schema.org/draft-07/schema#',
            definitions: {}
          };

          const files = fs.readdirSync('a2a')
            .filter(f => f.endsWith('.json') && f !== 'a2a-schema.json');

          files.forEach(file => {
            const content = JSON.parse(fs.readFileSync(path.join('a2a', file), 'utf8'));
            if (content.definitions) {
              Object.assign(combinedSchema.definitions, content.definitions);
            }
            fs.unlinkSync(path.join('a2a', file));
          });

          const cleanDescriptions = (obj) => {
            if (typeof obj !== 'object' || obj === null) return;
            for (const key in obj) {
              if (key === 'description' && typeof obj[key] === 'string') {
                let cleaned = obj[key]
                  .replace(/--8<--\s*\[start:\w+\]\s*/g, '')
                  .replace(/\s*--8<--\s*\[end:\w+\]/g, '')
                  .trim();
                if (cleaned === '') {
                  delete obj[key];
                } else {
                  obj[key] = cleaned;
                }
              } else if (typeof obj[key] === 'object') {
                cleanDescriptions(obj[key]);
              }
            }
          };
          cleanDescriptions(combinedSchema);

          fs.writeFileSync('a2a/a2a-schema.json', JSON.stringify(combinedSchema, null, 2));
          fs.writeFileSync('a2a/a2a-schema.yaml', yaml.dump(combinedSchema, {lineWidth: -1}));
        "
      - rm -rf a2a/tmp

  openapi:format:
    desc: "Format OpenAPI Spec"
    cmds:
      - prettier --write openapi.yaml

  openapi:lint:
    desc: "Lint OpenAPI spec"
    cmds:
      - spectral lint --verbose openapi.yaml
