version = 1

[install]
nodejs_24.pkg-path = "nodejs_24"
nodejs_24.version = "^24.13.0"
go.pkg-path = "go"
go.version = "1.25.7"
protobuf.pkg-path = "protobuf"
protobuf.version = "^33.5"
go-task.pkg-path = "go-task"
go-task.version = "^3.48.0"
buf.pkg-path = "buf"
buf.version = "^1.64.0"
claude-code.pkg-path = "claude-code"
claude-code.version = "^2.1.59"
prettier.pkg-path = "prettier"
prettier.version = "^3.6.2"