name: Sync Schemas and Create PR

on:
  workflow_dispatch:

jobs:
  sync-schemas:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install js-yaml
        run: npm install -g js-yaml

      - name: Download and convert schemas
        run: |
          task mcp-schema-download
          task a2a-schema-download

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b schemas-sync-$(date +'%Y%m%d') || git checkout schemas-sync-$(date +'%Y%m%d')
          git add a2a/a2a-schema.json a2a/a2a-schema.yaml mcp/mcp-schema.json mcp/mcp-schema.yaml
          git commit -m "chore: Sync schemas from MCP and A2A sources"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: Sync schemas from MCP and A2A sources"
          body: "Automated update of schemas from MCP and A2A sources."
          branch: schemas-sync-$(date +'%Y%m%d')
          base: main
          labels: |
            automation
