name: Sync Schemas and Create PR

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-schemas:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install js-yaml
        run: npm install -g js-yaml

      - name: Download and convert schemas
        run: |
          export NODE_PATH=$(npm root -g)
          task mcp-schema-download
          task a2a-schema-download

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Sync schemas from MCP and A2A sources"
          title: "chore: Sync schemas from MCP and A2A sources"
          body: |
            Automated update of schemas from MCP and A2A sources.

            This PR updates:
            - MCP schema from modelcontextprotocol/modelcontextprotocol
            - A2A schema from google-a2a/A2A
          branch: schemas-sync
          base: main
          delete-branch: true
